# Generated by Django 4.1.4 on 2022-12-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generaldata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.IntegerField(default=0, max_length=231)),
                ('desc', models.CharField(default='', max_length=451)),
            ],
        ),
    ]
