# Generated by Django 4.1.4 on 2022-12-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldata',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
